/**
 * Link variant of `integrations/shared/components/ConditionalReturn.tsx`.
 *
 * Sibling of `conditional-return-button` pinning the **other** branch of
 * the top-level `if/else` JSX return — confirms the runtime hydrates the
 * `<a class="conditional-link">` template path with the same fidelity as
 * the default branch. Same source file, different `props.variant` →
 * different SSR snapshot, identical client JS.
 *
 * Snapshots in `__snapshots__/conditional-return-link.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * conditional-return-link`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'conditional-return-link',
  componentName: 'ConditionalReturn',
  description:
    'ConditionalReturn link branch — anchor variant with reactive data-active',
  props: { variant: 'link' },
  interactions: [
    { type: 'expectContains', selector: '.conditional-link', text: 'link variant: 0' },
    {
      type: 'expectAttribute',
      selector: '.conditional-link',
      attribute: 'data-active',
      value: 'false',
    },
    { type: 'click', selector: '.conditional-link' },
    { type: 'expectContains', selector: '.conditional-link', text: 'link variant: 1' },
    {
      type: 'expectAttribute',
      selector: '.conditional-link',
      attribute: 'data-active',
      value: 'true',
    },
  ],
}

export const fixture = defineSharedFixture(spec)
