/**
 * Default (button) variant of `integrations/shared/components/ConditionalReturn.tsx`.
 *
 * Exercises top-level `if/else` JSX return (IRIfStatement) — the
 * compiler emits two register-able templates; this fixture pins the
 * `props.variant !== 'link'` branch (renders a `<button>`).
 *
 * Reactive surface beyond Counter:
 *   - `data-active={count() > 0}` — reactive attribute binding,
 *     distinct from textContent reactivity. Asserted via
 *     `expectAttribute` interaction steps.
 *
 * Snapshots in `__snapshots__/conditional-return-button.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * conditional-return-button`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'conditional-return-button',
  componentName: 'ConditionalReturn',
  description:
    'ConditionalReturn default branch — button variant with reactive data-active',
  // No `variant` prop → default `<button>` branch.
  props: {},
  interactions: [
    { type: 'expectContains', selector: '.conditional-button', text: 'button variant: 0' },
    {
      type: 'expectAttribute',
      selector: '.conditional-button',
      attribute: 'data-active',
      value: 'false',
    },
    { type: 'click', selector: '.conditional-button' },
    { type: 'expectContains', selector: '.conditional-button', text: 'button variant: 1' },
    {
      type: 'expectAttribute',
      selector: '.conditional-button',
      attribute: 'data-active',
      value: 'true',
    },
  ],
}

export const fixture = defineSharedFixture(spec)
