/**
 * Counter fixture lifted from `integrations/shared/components/Counter.tsx`.
 *
 * Single-scope variant: one `createSignal` + one `createMemo` against
 * three buttons. Anchors the fixture-hydrate corpus' baseline shape;
 * `toggle-shared` extends it to multi-scope hydration.
 *
 * Snapshots in `__snapshots__/counter-shared.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * counter-shared`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'counter-shared',
  componentName: 'Counter',
  description:
    'Counter with createSignal/createMemo lifted from integrations/shared',
  props: { initial: 0 },
  interactions: [
    { type: 'expectText', selector: '.counter-value', text: '0' },
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectText', selector: '.counter-value', text: '1' },
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectText', selector: '.counter-value', text: '2' },
    { type: 'expectContains', selector: '.counter-doubled', text: '4' },
    { type: 'click', selector: '.btn-decrement' },
    { type: 'expectText', selector: '.counter-value', text: '1' },
    { type: 'click', selector: '.btn-reset' },
    { type: 'expectText', selector: '.counter-value', text: '0' },
    { type: 'expectContains', selector: '.counter-doubled', text: '0' },
  ],
}

export const fixture = defineSharedFixture(spec)
