/**
 * PropsReactivityComparison fixture — second export of
 * `integrations/shared/components/ReactiveProps.tsx`.
 *
 * Sibling of `reactive-props`, but the **point of the test is what does
 * NOT update**: contrasts `props.xxx` access (reactive — `createMemo`
 * picks up the proxy read as a dependency) against destructured
 * `{ value, label } = props` (the destructure runs once at component
 * invocation, capturing the initial value; later parent updates do not
 * propagate).
 *
 * Locked behavior from spec/compiler.md:
 *   - PropsStyleChild's raw + computed values track parent's signal
 *   - DestructuredStyleChild's raw + computed values stay at initial,
 *     regardless of how many times the parent re-runs setCount
 *
 * Snapshots in `__snapshots__/props-reactivity-comparison.{html,client.js}`
 * are regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * props-reactivity-comparison`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

const propsStyle = '.props-style-child'
const destructured = '.destructured-style-child'

export const spec: SharedFixtureSpec = {
  id: 'props-reactivity-comparison',
  componentName: 'PropsReactivityComparison',
  // Second export of ReactiveProps.tsx — sourceFile pins the file basename
  // since it differs from the component name.
  sourceFile: 'ReactiveProps',
  description:
    'props.xxx vs destructured destructure — reactive prop access locks in vs captured-once semantics',
  // PropsReactivityComparison seeds its internal signal at 1 (not 0); both
  // children render with that initial value.
  props: {},
  interactions: [
    // Initial: parent count = 1 → both children show raw=1, computed=10.
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 1' },
    { type: 'expectText', selector: `${propsStyle} .child-raw-value`, text: '1' },
    { type: 'expectText', selector: `${propsStyle} .child-computed-value`, text: '10' },
    { type: 'expectText', selector: `${destructured} .child-raw-value`, text: '1' },
    { type: 'expectText', selector: `${destructured} .child-computed-value`, text: '10' },

    // Parent +1 → props-style tracks (raw=2, memo=20); destructured stays at 1/10.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectContains', selector: '.parent-count', text: 'Count: 2' },
    { type: 'expectText', selector: `${propsStyle} .child-raw-value`, text: '2' },
    { type: 'expectText', selector: `${propsStyle} .child-computed-value`, text: '20' },
    { type: 'expectText', selector: `${destructured} .child-raw-value`, text: '1' },
    { type: 'expectText', selector: `${destructured} .child-computed-value`, text: '10' },

    // One more click — divergence widens, destructured still pinned.
    { type: 'click', selector: '.btn-increment' },
    { type: 'expectText', selector: `${propsStyle} .child-raw-value`, text: '3' },
    { type: 'expectText', selector: `${propsStyle} .child-computed-value`, text: '30' },
    { type: 'expectText', selector: `${destructured} .child-raw-value`, text: '1' },
    { type: 'expectText', selector: `${destructured} .child-computed-value`, text: '10' },
  ],
}

export const fixture = defineSharedFixture(spec)
