/**
 * Text-content HTML-escaping fixture (#1694), sourced from
 * `integrations/shared/components/TextEscape.tsx`.
 *
 * Pins the parallel of the #1692 attribute-escape work for **text
 * content**: `{label}` carries `< > & " '`, so the client template emits
 * `<!--bf:sN-->${escapeText(label)}<!--/-->`. The CSR-conformance compare
 * asserts the client-rendered bytes match the SSR-escaped snapshot; the
 * fixture-hydrate interactions assert the `<b>` in `label` stays literal
 * text (no injection) and the reactive count updates.
 *
 * Snapshots in `__snapshots__/text-escape.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * text-escape`.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

export const spec: SharedFixtureSpec = {
  id: 'text-escape',
  componentName: 'TextEscape',
  description:
    'text-content HTML-escaping — metacharacter label + reactive count (#1694)',
  // Metacharacters limited to `& < >` — the parsing-significant text set.
  // `"` / `'` are exercised by `escape-text.test.ts`; embedding them here
  // would break the Go adapter's test harness, which serialises string
  // props into a Go composite literal (an unescaped `"` closes the Go
  // string). `& < >` are the chars that actually corrupt HTML parsing.
  props: { label: `Tom & Jerry <b>bold</b> & <i>italic</i>` },
  interactions: [
    // The `<b>` survives as literal text (escaped), not a real element.
    { type: 'expectContains', selector: '.label', text: 'Tom & Jerry <b>bold</b>' },
    { type: 'expectContains', selector: 'button', text: 'count: 0' },
    { type: 'click', selector: 'button' },
    { type: 'expectContains', selector: 'button', text: 'count: 1' },
  ],
}

export const fixture = defineSharedFixture(spec)
