/**
 * Toggle fixture lifted from `integrations/shared/components/Toggle.tsx`.
 *
 * Multi-scope variant of `counter-shared`: parent `Toggle` plus three
 * sibling `ToggleItem`s (rendered via a keyed `.map`) exercise both child
 * composition and signal isolation between sibling instances.
 *
 * Snapshots in `__snapshots__/toggle-shared.{html,client.js}` are
 * regenerated by `bun run packages/adapter-tests/scripts/snapshot.ts
 * toggle-shared`. The frozen HTML carries random child ScopeIDs from the
 * SSR pass; the client JS reads them back from `bf-s` at hydrate time,
 * so internal consistency within the snapshot is the only invariant.
 */

import { defineSharedFixture, type SharedFixtureSpec } from './_helpers'

// Direct-child CSS selectors against `.settings-panel`'s element children
// (comment loop markers are ignored by nth-child): h3 is :nth-child(1),
// the three ToggleItems are :nth-child(2..4).
const item = (n: 1 | 2 | 3) =>
  `.toggle-item:nth-child(${n + 1}) button` as const

export const spec: SharedFixtureSpec = {
  id: 'toggle-shared',
  componentName: 'Toggle',
  description:
    'Toggle parent + ToggleItem children (loop with key, multi-scope hydration)',
  props: {
    toggleItems: [
      { label: 'Setting 1', defaultOn: true },
      { label: 'Setting 2', defaultOn: false },
      { label: 'Setting 3' },
    ],
  },
  interactions: [
    // Initial state from defaultOn props.
    { type: 'expectText', selector: item(1), text: 'ON' },
    { type: 'expectText', selector: item(2), text: 'OFF' },
    { type: 'expectText', selector: item(3), text: 'OFF' },
    // Flip Setting 1.
    { type: 'click', selector: item(1) },
    { type: 'expectText', selector: item(1), text: 'OFF' },
    // Setting 2 unaffected (signal isolation between sibling scopes).
    { type: 'expectText', selector: item(2), text: 'OFF' },
    // Flip Setting 2 — Setting 3 must still be OFF.
    { type: 'click', selector: item(2) },
    { type: 'expectText', selector: item(2), text: 'ON' },
    { type: 'expectText', selector: item(3), text: 'OFF' },
    // Flip Setting 3, then re-verify the others survived the previous clicks.
    { type: 'click', selector: item(3) },
    { type: 'expectText', selector: item(3), text: 'ON' },
    { type: 'expectText', selector: item(1), text: 'OFF' },
    { type: 'expectText', selector: item(2), text: 'ON' },
  ],
}

export const fixture = defineSharedFixture(spec)
